### ISSUE TITLE
Error: Faulty Request There was an error with the request. The "client_id" field is invalid.

### ISSUE THREAD

**Issue by CarlSinclair** [Zegnat/php-mintoken#12]
This is an issue with selfauth but I'm hoping I can get some guidance here. I've also set up php-mintoken but I don't see how it even connects to selfauth. What am I missing here?

I've regenerated the config file several times and I keep getting the same error. Tried on a subdomain (http://auth.domain.tld and https://auth.domain.tld), on a subfolder (http://domain.tld/auth and https://domain.tld/auth) like in the guide, and even on the root domain (http://domain.tld and https://domain.tld). I even tried with www in the username (http://www.domain.tld and https://www.domain.tld).

`<?php`
`define('APP_URL', 'http://auth.domain.tld/');`
`define('APP_KEY', ''>`
`define('USER_HASH', '');`
`define('USER_URL', 'https://domain.tld');`

**Comment by Zegnat** [comment]
What client are you trying to give a token to?

Mintoken was required for older versions of the IndieAuth specification, where the authorization endpoint and token endpoint were completely separated. The client would need to do a request to the authorization endpoint (Selfauth) which would issue a “code” to the client that can then be exchanged at the token endpoint (Mintoken).

If you are getting an error about the client_id, that sounds like the very first step from your client to Selfauth is already failing. As Mintoken never throws that error. Even if you can get that part to work, it is not guaranteed that the client is able to talk to Mintoken for a code exchange though.

Your configuration might be correct already. Mintoken is not configured to use any specific Selfauth instance. A single instance of Mintoken could serve to do code exchanges for multiple Selfauth instances. Mintoken is also not configured to do (or know) anything about different clients. It simply received a “code”, checks with the given authorization endpoint (discovered from a `?me=` query value) for that code, and if successful it issues a token.

**Comment by CarlSinclair** [comment]
I'm trying to setup IndieAuth for just one domain. Maybe I've misunderstood all of this, but I setup selfauth (and mintoken) on the same server as this domain and configured them to use this domain so I can log into IndieAuth-enabled websites using this domain. I'm not trying to setup an IndieAuth login portal on my own website.

I've tested it against every IndieAuth login portal I could find, all have been failing with the same errors (unique to each one) no matter what I do, which tells me they aren't detecting anything I've setup.

I've already opened an issue with selfauth as well but have yet to receive a response. Am I understanding you correctly in that mintoken is no longer required for an IndieAuth setup? I've looked at other IndieAuth implementations and they've all either been abandoned or are far more complex to setup than selfauth.

**Comment by Zegnat** [comment]
Sorry, I must have missed the issue on Selfauth for some reason.

Mintoken has never been a requirement. I still run Selfauth without it to authenticate with the IndieWeb wiki myself. Mintoken is only needed if you need long-lived token management for things like Micropub clients, as Selfauth does not issue tokens.

I will close this issue and continue this on the Selfauth issue tracker instead. Inklings-io/selfauth#54
